[platformio]
default_envs = esp32
extra_configs = secrets.ini

[common]
build_flags = -std=gnu++17 -DARDUINOJSON_ENABLE_PROGMEM=0
lib_deps =
    ESP32Async/ESPAsyncWebServer@^3.7.0
    ESP32Async/AsyncTCP@^3.3.0
    bblanchon/ArduinoJson@^7.2.0

[env:esp32]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs
board_build.partitions = partitions.csv
extra_scripts = pre:extra_script.py
build_flags = ${common.build_flags}
lib_deps = ${common.lib_deps}

[env:esp32-dev]
extends = env:esp32
build_flags = ${common.build_flags} -DDEV_STA -DDICE_FIXED=20

[env:native]
platform = native
test_framework = unity
build_flags = -std=gnu++17
lib_deps = throwtheswitch/Unity
