[platformio]
default_envs = esp32
extra_configs = secrets.ini

[common]
build_flags = -std=gnu++17 -DARDUINOJSON_ENABLE_PROGMEM=0
lib_deps =
    ESP32Async/ESPAsyncWebServer@^3.7.0
    ESP32Async/AsyncTCP@^3.3.0
    bblanchon/ArduinoJson@^7.2.0
    links2004/WebSockets@^2.7.3

[env:esp32]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs
board_build.partitions = partitions.csv
extra_scripts = pre:extra_script.py
build_unflags = -fno-exceptions
build_flags = ${common.build_flags} -fexceptions
lib_deps = ${common.lib_deps}

[env:esp32-dev]
extends = env:esp32
build_flags = ${common.build_flags} -fexceptions -DDEV_STA -DPIN_LOCK_MS=1500
