// app/conformance/haggle-vectors.json -> esp/test/test_engine/vectors.inc (plain C data, no JSON parser needed natively)
import { readFileSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
const root = join(dirname(fileURLToPath(import.meta.url)), '..', '..');
const v = JSON.parse(readFileSync(join(root, 'app/conformance/haggle-vectors.json'), 'utf8'));
const n = (x) => (x === null || x === undefined ? '0' : JSON.stringify(x));
const s = (x) => JSON.stringify(x ?? '');
const steps = [], cases = [];
for (const c of v.cases) {
  cases.push(`{${n(c.X)},${s(c.type)},${n(c.bonusRep)},${n(c.start.rep)},${n(c.start.maxRep)},${n(c.start.price)},${s(c.start.status)},${steps.length},${c.steps.length}}`);
  for (const t of c.steps) {
    const i = t.in, o = t.out, r = i.rolls;
    const head = `{${n(i.Y)},${s(i.approach)},${n(i.bonus)},{${r[0] ?? 0},${r[1] ?? 0}},${r.length},${n(i.dcMod ?? 0)}`;
    steps.push(o.error
      ? `${head},1,${s(o.error)},"",0,0,0,0,0,0,"",0,0,0}`
      : `${head},0,"",${s(o.outcome)},${o.roll === null ? 0 : 1},${n(o.roll)},${o.total === null ? 0 : 1},${n(o.total)},${n(o.repLoss)},${n(o.price)},${s(o.status)},${n(o.rep)},${o.lastY === null ? 0 : 1},${n(o.lastY)}}`);
  }
}
writeFileSync(join(root, 'esp/test/test_engine/vectors.inc'),
  `// generated by esp/tools/gen-vectors.mjs - do not edit\nstatic const VCase VCASES[] = {\n${cases.join(',\n')}\n};\nstatic const VStep VSTEPS[] = {\n${steps.join(',\n')}\n};\nstatic const int NCASES = ${cases.length};\n`);
console.log(cases.length, 'cases', steps.length, 'steps');
