# Writes esp/src/relay_ca.h from root certificates already in the Windows certificate store (nothing is downloaded).
# The Worker's chain ends at ISRG Root X1 (the server sends the X1-signed ISRG Root X2 in between). X2 is embedded too when Windows has it.
$roots = 'ISRG Root X1', 'ISRG Root X2'
$pem = ''
foreach ($cn in $roots) {
  $c = Get-ChildItem Cert:\CurrentUser\Root, Cert:\LocalMachine\Root | Where-Object { $_.Subject -match "CN=$cn(,|$)" -and $_.Subject -eq $_.Issuer } | Select-Object -First 1
  if (-not $c) { Write-Host "$cn not in the Windows store, skipped"; continue }
  $b64 = [Convert]::ToBase64String($c.RawData, 'InsertLineBreaks').Replace("`r", '')
  $pem += "-----BEGIN CERTIFICATE-----`n$b64`n-----END CERTIFICATE-----`n"
  Write-Host "$cn  sha1 $($c.Thumbprint)  expires $($c.NotAfter.ToString('yyyy-MM-dd'))"
}
$lines = ($pem.TrimEnd("`n") -split "`n" | ForEach-Object { '  "' + $_ + '\n"' }) -join "`n"
$out = "// Generated by tools/relay-ca.ps1 from the Windows root store. Roots that verify the Cloudflare Worker's TLS chain.`n#pragma once`nstatic const char RELAY_CA_PEM[] =`n$lines;`n"
[IO.File]::WriteAllText((Join-Path $PSScriptRoot '..\src\relay_ca.h'), $out, (New-Object Text.UTF8Encoding $false))
Write-Host "relay_ca.h written ($($out.Length) chars)"
